#!/usr/bin/env bash
# check_all_gates.sh — Run all phase gate checks in sequence
# AUTO-GENERATED by gen_phase_gates.py from project.yaml
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

TOTAL_PASSED=0
TOTAL_FAILED=0

echo ">>> Running gate 0: Phase 0 — Environment & Data Acquisition"
if bash "$SCRIPT_DIR/check_phase_0.sh"; then
    TOTAL_PASSED=$((TOTAL_PASSED + 1))
else
    TOTAL_FAILED=$((TOTAL_FAILED + 1))
    echo "!!! Gate 0 failed — stopping."
    exit 1
fi
echo ''

echo ">>> Running gate 1: Phase 1 — Crypto Detection Engine"
if bash "$SCRIPT_DIR/check_phase_1.sh"; then
    TOTAL_PASSED=$((TOTAL_PASSED + 1))
else
    TOTAL_FAILED=$((TOTAL_FAILED + 1))
    echo "!!! Gate 1 failed — stopping."
    exit 1
fi
echo ''

echo ">>> Running gate 2: Phase 2 — Priority Scoring"
if bash "$SCRIPT_DIR/check_phase_2.sh"; then
    TOTAL_PASSED=$((TOTAL_PASSED + 1))
else
    TOTAL_FAILED=$((TOTAL_FAILED + 1))
    echo "!!! Gate 2 failed — stopping."
    exit 1
fi
echo ''

echo ">>> Running gate 3: Phase 3 — Migration Recommendations & Findings"
if bash "$SCRIPT_DIR/check_phase_3.sh"; then
    TOTAL_PASSED=$((TOTAL_PASSED + 1))
else
    TOTAL_FAILED=$((TOTAL_FAILED + 1))
    echo "!!! Gate 3 failed — stopping."
    exit 1
fi
echo ''

echo "========================================="
echo "All $TOTAL_PASSED phase gates PASSED."
echo "========================================="
