#!/usr/bin/env python3
"""check_rubric.py — Rubric/FAQ compliance checker for report files.

Auto-generated by gen_rubric_checker.py from project.yaml.
Re-run generator after changing project.yaml authority/audit configuration.

Project: Post-Quantum Cryptography Migration Analyzer

This script:
  1. Reads the rubric source file and extracts requirement items.
  2. Reads the FAQ source file and extracts FAQ questions.
  3. Optionally reads a filled RUBRIC_TRACEABILITY.md for pre-mapped sections.
  4. Reads the report file (.tex or .md) and checks coverage of each item.
  5. Flags items as ADDRESSED, PARTIAL, or GAP.
  6. Outputs a coverage report and generates/updates RUBRIC_TRACEABILITY.md.

Exit codes:
  0 — Coverage >= 80% and 0 CRITICAL gaps
  1 — Coverage below threshold or CRITICAL gaps found
"""
import argparse
import os
import re
import sys
from pathlib import Path
from typing import Optional


# ---------------------------------------------------------------------------
# Configuration (derived from project.yaml at generation time)
# ---------------------------------------------------------------------------

DEFAULT_RUBRIC_SOURCE = "docs/PROJECT_BRIEF.md"
DEFAULT_FAQ_SOURCE = "None"
COVERAGE_THRESHOLD = 80

CRITICAL_CATEGORIES = [
    # (none configured)
]

# Common gap patterns from UL/RL experience — used for enhanced gap detection
GAP_PATTERNS = [
    "distance metric justification", "similarity metric justification", "hyperparameter search range",
    "hyperparameter sensitivity", "initialization choice", "convergence criteria",
    "reward function", "objective function", "ablation analysis",
    "noise sensitivity", "suggested improvement",
]

# Keywords that help match rubric items to report sections
RUBRIC_KEYWORDS = [
    "must", "should", "required", "explain", "justify", "describe",
    "compare", "analyze", "discuss", "evaluate", "plot", "table",
    "figure", "report", "show", "demonstrate", "provide", "include",
    "convergence", "hyperparameter", "metric", "distance", "similarity", "initialization",
    "reward", "objective", "ablation", "noise", "improvement", "baseline",
    "experiment",
]


# ---------------------------------------------------------------------------
# Rubric / FAQ extraction
# ---------------------------------------------------------------------------

# Patterns for extracting numbered requirements, bullets, or markdown headers
_NUMBERED_RE = re.compile(
    r"^\s*"                   # leading whitespace
    r"(?:"
    r"(\d+)[.)\s]"           # numbered: "1." or "1)" or "1 "
    r"|"
    r"[-*+]\s"               # bullet: "- " or "* " or "+ "
    r"|"
    r"(#{1,4})\s"           # markdown header: "## "
    r")"
    r"\s*(.*)"               # the requirement text
)

_FAQ_Q_RE = re.compile(
    r"^\s*"
    r"(?:"
    r"Q\s*[:.]?\s*"         # Q: or Q. prefix
    r"|"
    r"(?:Question|FAQ)\s*\d*\s*[:.]?\s*"  # Question 1: or FAQ:
    r"|"
    r"(\d+)[.)\s]\s*"      # numbered
    r")"
    r"(.*\?.*)",              # text containing a question mark
    re.IGNORECASE
)


def extract_rubric_items(text: str) -> list[dict]:
    """Extract individual requirement items from rubric source text.

    Returns list of dicts with keys: id, text, category, is_critical.
    """
    items = []
    lines = text.splitlines()
    current_category = "General"
    item_num = 0

    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue

        # Detect category headers (## Category or ALL CAPS lines)
        if stripped.startswith("#"):
            hdr = stripped.lstrip("#").strip()
            if hdr:
                current_category = hdr
            continue
        if stripped.isupper() and len(stripped) > 3 and len(stripped) < 80:
            current_category = stripped.title()
            continue

        m = _NUMBERED_RE.match(line)
        if m:
            num_str = m.group(1)
            header_level = m.group(2)
            text_part = m.group(3) or ""
            text_part = text_part.strip()

            if not text_part or len(text_part) < 5:
                continue

            # Skip if it looks like a section header for a category
            if header_level and not any(
                kw in text_part.lower() for kw in RUBRIC_KEYWORDS
            ):
                current_category = text_part
                continue

            item_num += 1
            item_id = f"R-{item_num:02d}"
            is_critical = any(
                cat.lower() in current_category.lower()
                for cat in CRITICAL_CATEGORIES
            ) or any(
                kw in text_part.lower()
                for kw in ("must", "required", "critical")
            )

            items.append({
                "id": item_id,
                "text": text_part,
                "category": current_category,
                "is_critical": is_critical,
            })

    return items


def extract_faq_items(text: str) -> list[dict]:
    """Extract FAQ questions from FAQ source text.

    Returns list of dicts with keys: id, text.
    """
    items = []
    lines = text.splitlines()
    faq_num = 0

    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue

        m = _FAQ_Q_RE.match(stripped)
        if m:
            # group(1) is the optional number, group(2) is the question text
            q_text = m.group(2) or m.group(0)
            q_text = q_text.strip()
            if len(q_text) < 5:
                continue
            faq_num += 1
            items.append({
                "id": f"FAQ-{faq_num:02d}",
                "text": q_text,
            })
            continue

        # Also catch lines that end with "?" even without Q: prefix
        if stripped.endswith("?") and len(stripped) > 10:
            faq_num += 1
            items.append({
                "id": f"FAQ-{faq_num:02d}",
                "text": stripped,
            })

    return items


# ---------------------------------------------------------------------------
# Traceability matrix parsing
# ---------------------------------------------------------------------------

def parse_traceability(text: str) -> dict[str, dict]:
    """Parse a filled RUBRIC_TRACEABILITY.md file.

    Returns a dict mapping item_id -> {section, status, evidence}.
    """
    mappings: dict[str, dict] = {}
    lines = text.splitlines()

    for line in lines:
        stripped = line.strip()
        if not stripped.startswith("|"):
            continue

        cells = [c.strip() for c in stripped.split("|")]
        # Filter out empty cells from leading/trailing pipes
        cells = [c for c in cells if c]

        if len(cells) < 4:
            continue

        item_id = cells[0].strip()
        # Skip header rows and separator rows
        if item_id in ("#", "---", "") or item_id.startswith("-"):
            continue
        if not (item_id.startswith("R-") or item_id.startswith("FAQ-") or item_id.startswith("EC-")):
            continue

        # Extract mapped section and status
        # Rubric table: # | Category | Requirement | Report Section | ... | Status
        # FAQ table: # | Question | Report Section | ... | Status
        if item_id.startswith("R-"):
            section = cells[3] if len(cells) > 3 else ""
            status = cells[5] if len(cells) > 5 else ""
            evidence = cells[6] if len(cells) > 6 else ""
        else:
            section = cells[2] if len(cells) > 2 else ""
            status = cells[4] if len(cells) > 4 else ""
            evidence = cells[5] if len(cells) > 5 else ""

        # Clean template placeholders
        for placeholder in ("{{SECTION}}", "{{PARA_OR_LINE}}", "{{ADDRESSED/GAP/PARTIAL}}",
                            "{{QUOTE_OR_REF}}", "{{DATE}}"):
            if section == placeholder:
                section = ""
            if status == placeholder:
                status = ""

        mappings[item_id] = {
            "section": section,
            "status": status.upper() if status else "",
            "evidence": evidence,
        }

    return mappings


# ---------------------------------------------------------------------------
# Report reading and section extraction
# ---------------------------------------------------------------------------

def read_report_sections(report_path: Path) -> dict[str, str]:
    """Read a report file and split it into sections.

    Returns dict mapping section_name -> section_text.
    Also includes a special "_full" key with the entire text.
    """
    text = report_path.read_text(encoding="utf-8", errors="replace")
    sections: dict[str, str] = {"_full": text}

    is_latex = report_path.suffix.lower() in (".tex", ".latex")

    if is_latex:
        # Split on LaTeX section commands
        sec_re = re.compile(
            r"\\(?:section|subsection|subsubsection)\{([^{}]+)\}",
        )
    else:
        # Split on Markdown headers
        sec_re = re.compile(r"^(#{1,4})\s+(.+)$", re.MULTILINE)

    if is_latex:
        parts = sec_re.split(text)
        # parts: [preamble, sec1_name, sec1_text, sec2_name, sec2_text, ...]
        current_name = "_preamble"
        current_text = ""
        i = 0
        while i < len(parts):
            if sec_re.match(parts[i]) if i > 0 else False:
                sections[current_name] = current_text
                current_name = parts[i]
                current_text = ""
            else:
                current_text += parts[i]
            i += 1
        sections[current_name] = current_text

        # Re-parse more carefully
        sections = {"_full": text}
        matches = list(sec_re.finditer(text))
        for idx, match in enumerate(matches):
            name = match.group(1).strip()
            start = match.end()
            end = matches[idx + 1].start() if idx + 1 < len(matches) else len(text)
            sections[name] = text[start:end]
    else:
        matches = list(sec_re.finditer(text))
        for idx, match in enumerate(matches):
            name = match.group(2).strip()
            start = match.end()
            end = matches[idx + 1].start() if idx + 1 < len(matches) else len(text)
            sections[name] = text[start:end]

    return sections


# ---------------------------------------------------------------------------
# Coverage checking
# ---------------------------------------------------------------------------

def compute_keyword_score(requirement_text: str, section_text: str) -> float:
    """Compute a keyword overlap score between a requirement and section text.

    Returns a float between 0.0 and 1.0.
    """
    # Extract significant words from the requirement
    req_words = set(
        w.lower() for w in re.findall(r"\b[a-zA-Z]{3,}\b", requirement_text)
    )
    # Remove very common words
    stopwords = {
        "the", "and", "for", "are", "but", "not", "you", "all", "can",
        "had", "her", "was", "one", "our", "out", "has", "have", "been",
        "that", "this", "with", "from", "they", "will", "what", "when",
        "make", "like", "each", "does", "how", "its", "may", "than",
        "use", "used", "using", "your", "should", "must", "also",
        "which", "their", "would", "about", "into", "more", "some",
    }
    req_words -= stopwords

    if not req_words:
        return 0.0

    section_lower = section_text.lower()
    matched = sum(1 for w in req_words if w in section_lower)

    return matched / len(req_words)


def check_gap_patterns(section_text: str) -> list[str]:
    """Check which common gap patterns are missing from a section.

    Returns list of gap pattern descriptions that are NOT found.
    """
    missing = []
    section_lower = section_text.lower()

    pattern_checks = [
        ("distance metric justification",
         r"(?:distance|similarity)\s+metric.*(?:because|since|chosen|select|justif)"),
        ("similarity metric justification",
         r"(?:distance|similarity).*(?:reason|rationale|motivation|why)"),
        ("hyperparameter search range",
         r"(?:hyperparameter|hyper-parameter|hp).*(?:range|search|grid|sweep|tuning)"),
        ("hyperparameter sensitivity",
         r"(?:hyperparameter|hyper-parameter|hp).*(?:sensitiv|impact|effect|vary)"),
        ("initialization choice",
         r"(?:initial|seed|start|q.?0|bootstrap).*(?:choice|select|set|value)"),
        ("convergence criteria",
         r"(?:converg|stop|terminat).*(?:criteri|threshold|condition|when)"),
        ("reward function details",
         r"(?:reward|objective)\s+(?:function|signal|formul)"),
        ("ablation analysis",
         r"(?:ablat|remov|without|drop).*(?:analys|study|experiment|result)"),
        ("noise sensitivity",
         r"(?:noise|perturb|robust).*(?:sensitiv|analys|test|effect)"),
        ("suggested improvements",
         r"(?:future|improv|suggest|recommend|next|limit).*(?:work|step|direction|could)"),
    ]

    for name, pattern in pattern_checks:
        if not re.search(pattern, section_lower):
            missing.append(name)

    return missing


def check_item_coverage(
    item: dict,
    sections: dict[str, str],
    traceability: dict[str, dict],
) -> dict:
    """Check whether a single rubric/FAQ item is covered in the report.

    Returns a result dict with: id, text, status, section, score, details.
    """
    item_id = item["id"]
    item_text = item["text"]

    # If traceability matrix has a mapping, use it
    if item_id in traceability:
        mapped = traceability[item_id]
        if mapped["status"] in ("ADDRESSED", "PARTIAL", "GAP", "N/A"):
            mapped_section = mapped["section"]
            # Verify the mapped section actually exists and has content
            if mapped_section and mapped_section in sections:
                score = compute_keyword_score(item_text, sections[mapped_section])
                if score >= 0.4:
                    return {
                        "id": item_id,
                        "text": item_text,
                        "status": "ADDRESSED",
                        "section": mapped_section,
                        "score": score,
                        "details": f"Traceability-mapped, keyword score {score:.2f}",
                        "is_critical": item.get("is_critical", False),
                        "category": item.get("category", ""),
                    }
                elif score >= 0.2:
                    return {
                        "id": item_id,
                        "text": item_text,
                        "status": "PARTIAL",
                        "section": mapped_section,
                        "score": score,
                        "details": f"Traceability-mapped but low keyword overlap ({score:.2f})",
                        "is_critical": item.get("is_critical", False),
                        "category": item.get("category", ""),
                    }
            # If mapped section not found or empty, fall through to keyword search

    # Keyword-based search across all sections
    best_section = None
    best_score = 0.0

    for sec_name, sec_text in sections.items():
        if sec_name == "_full":
            continue
        score = compute_keyword_score(item_text, sec_text)
        if score > best_score:
            best_score = score
            best_section = sec_name

    # If no section matched well, try the full text
    if best_score < 0.2:
        full_score = compute_keyword_score(item_text, sections.get("_full", ""))
        if full_score > best_score:
            best_score = full_score
            best_section = "(full text search)"

    # Determine status based on score
    if best_score >= 0.5:
        status = "ADDRESSED"
    elif best_score >= 0.25:
        status = "PARTIAL"
    else:
        status = "GAP"

    details = f"Best keyword score {best_score:.2f} in '{best_section or 'none'}'"

    return {
        "id": item_id,
        "text": item_text,
        "status": status,
        "section": best_section or "",
        "score": best_score,
        "details": details,
        "is_critical": item.get("is_critical", False),
        "category": item.get("category", ""),
    }


# ---------------------------------------------------------------------------
# Traceability generation
# ---------------------------------------------------------------------------

def generate_traceability(
    rubric_results: list[dict],
    faq_results: list[dict],
    rubric_source: str,
    faq_source: str,
    output_path: Path,
) -> None:
    """Generate or update RUBRIC_TRACEABILITY.md from check results."""
    lines = [
        "# Rubric & FAQ Traceability Matrix",
        "",
        "> **Auto-generated by check_rubric.py**",
        f"> **Rubric source:** `{rubric_source}`",
        f"> **FAQ source:** `{faq_source}`",
        "",
        "---",
        "",
        "## Rubric Items",
        "",
        f"**Source:** `{rubric_source}`",
        "",
        "| # | Category | Requirement | Report Section | Status | Score | Details |",
        "|---|----------|-------------|---------------|--------|-------|---------|",
    ]

    for r in rubric_results:
        req_text = r["text"][:80] + ("..." if len(r["text"]) > 80 else "")
        req_text = req_text.replace("|", "\\|")
        lines.append(
            f"| {r['id']} | {r.get('category', '')} | {req_text} "
            f"| {r['section']} | {r['status']} | {r['score']:.2f} | {r['details']} |"
        )

    lines.extend([
        "",
        "---",
        "",
        "## FAQ Items",
        "",
        f"**Source:** `{faq_source}`",
        "",
        "| # | Question | Report Section | Status | Score | Details |",
        "|---|----------|---------------|--------|-------|---------|",
    ])

    for r in faq_results:
        q_text = r["text"][:80] + ("..." if len(r["text"]) > 80 else "")
        q_text = q_text.replace("|", "\\|")
        lines.append(
            f"| {r['id']} | {q_text} | {r['section']} "
            f"| {r['status']} | {r['score']:.2f} | {r['details']} |"
        )

    # Coverage summary
    all_results = rubric_results + faq_results
    total = len(all_results)
    addressed = sum(1 for r in all_results if r["status"] == "ADDRESSED")
    partial = sum(1 for r in all_results if r["status"] == "PARTIAL")
    gaps = sum(1 for r in all_results if r["status"] == "GAP")
    pct = (addressed / total * 100) if total > 0 else 0

    rubric_total = len(rubric_results)
    rubric_addr = sum(1 for r in rubric_results if r["status"] == "ADDRESSED")
    rubric_pct = (rubric_addr / rubric_total * 100) if rubric_total > 0 else 0

    faq_total = len(faq_results)
    faq_addr = sum(1 for r in faq_results if r["status"] == "ADDRESSED")
    faq_pct = (faq_addr / faq_total * 100) if faq_total > 0 else 0

    lines.extend([
        "",
        "---",
        "",
        "## Coverage Summary",
        "",
        "```",
        f"Rubric:  {rubric_addr}/{rubric_total} ADDRESSED ({rubric_pct:.0f}%)",
        f"FAQ:     {faq_addr}/{faq_total} ADDRESSED ({faq_pct:.0f}%)",
        f"Overall: {addressed}/{total} ADDRESSED ({pct:.0f}%)",
        f"",
        f"PARTIAL items: {partial}",
        f"GAP items:     {gaps}",
        "```",
        "",
    ])

    # List gaps
    gap_items = [r for r in all_results if r["status"] == "GAP"]
    if gap_items:
        lines.append("### GAP Items Requiring Attention")
        lines.append("")
        for r in gap_items:
            critical_tag = " **[CRITICAL]**" if r.get("is_critical") else ""
            lines.append(f"- **{r['id']}**{critical_tag}: {r['text'][:100]}")
        lines.append("")

    # List partials
    partial_items = [r for r in all_results if r["status"] == "PARTIAL"]
    if partial_items:
        lines.append("### PARTIAL Items Requiring Expansion")
        lines.append("")
        for r in partial_items:
            lines.append(f"- **{r['id']}**: {r['text'][:100]} (score: {r['score']:.2f})")
        lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n")
    print(f"  Traceability written: {output_path}")


# ---------------------------------------------------------------------------
# Main checking pipeline
# ---------------------------------------------------------------------------

def run_checks(
    report_path: Path,
    rubric_source: Path,
    faq_source: Path,
    traceability_path: Optional[Path] = None,
) -> tuple[list[dict], list[dict], list[str]]:
    """Run all rubric/FAQ coverage checks.

    Returns (rubric_results, faq_results, gap_pattern_warnings).
    """
    # Step 1: Extract rubric items
    rubric_items = []
    if rubric_source.exists():
        rubric_text = rubric_source.read_text(encoding="utf-8", errors="replace")
        rubric_items = extract_rubric_items(rubric_text)
        print(f"  Extracted {len(rubric_items)} rubric items from {rubric_source}")
    else:
        print(f"  WARNING: Rubric source not found: {rubric_source}", file=sys.stderr)

    # Step 2: Extract FAQ items
    faq_items = []
    if faq_source.exists():
        faq_text = faq_source.read_text(encoding="utf-8", errors="replace")
        faq_items = extract_faq_items(faq_text)
        print(f"  Extracted {len(faq_items)} FAQ items from {faq_source}")
    else:
        print(f"  WARNING: FAQ source not found: {faq_source}", file=sys.stderr)

    # Step 3: Load traceability matrix if provided
    traceability: dict[str, dict] = {}
    if traceability_path and traceability_path.exists():
        trace_text = traceability_path.read_text(encoding="utf-8", errors="replace")
        traceability = parse_traceability(trace_text)
        print(f"  Loaded {len(traceability)} traceability mappings from {traceability_path}")

    # Step 4: Read and parse report
    if not report_path.exists():
        print(f"  ERROR: Report file not found: {report_path}", file=sys.stderr)
        # Return everything as GAP
        rubric_results = [
            {"id": it["id"], "text": it["text"], "status": "GAP",
             "section": "", "score": 0.0, "details": "Report file not found",
             "is_critical": it.get("is_critical", False),
             "category": it.get("category", "")}
            for it in rubric_items
        ]
        faq_results = [
            {"id": it["id"], "text": it["text"], "status": "GAP",
             "section": "", "score": 0.0, "details": "Report file not found",
             "is_critical": False, "category": ""}
            for it in faq_items
        ]
        return rubric_results, faq_results, []

    sections = read_report_sections(report_path)
    print(f"  Parsed {len(sections) - 1} sections from {report_path}")

    # Step 5: Check each rubric item
    rubric_results = []
    for item in rubric_items:
        result = check_item_coverage(item, sections, traceability)
        rubric_results.append(result)

    # Step 6: Check each FAQ item
    faq_results = []
    for item in faq_items:
        result = check_item_coverage(item, sections, traceability)
        faq_results.append(result)

    # Step 7: Check common gap patterns against full report text
    full_text = sections.get("_full", "")
    gap_warnings = check_gap_patterns(full_text)

    return rubric_results, faq_results, gap_warnings


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

def print_coverage_report(
    rubric_results: list[dict],
    faq_results: list[dict],
    gap_warnings: list[str],
) -> None:
    """Print a human-readable coverage report."""
    all_results = rubric_results + faq_results
    total = len(all_results)
    addressed = sum(1 for r in all_results if r["status"] == "ADDRESSED")
    partial = sum(1 for r in all_results if r["status"] == "PARTIAL")
    gaps = sum(1 for r in all_results if r["status"] == "GAP")
    pct = (addressed / total * 100) if total > 0 else 0
    critical_gaps = sum(
        1 for r in all_results
        if r["status"] == "GAP" and r.get("is_critical")
    )

    print()
    print("=" * 70)
    print("RUBRIC / FAQ COMPLIANCE CHECK")
    print("=" * 70)
    print(f"  ADDRESSED: {addressed}")
    print(f"  PARTIAL:   {partial}")
    print(f"  GAP:       {gaps}")
    print(f"  Coverage:  {pct:.0f}% (threshold: {COVERAGE_THRESHOLD}%)")
    if critical_gaps:
        print(f"  CRITICAL GAPS: {critical_gaps}")
    print("-" * 70)

    # Per-item details
    if rubric_results:
        print()
        print("RUBRIC ITEMS:")
        for r in rubric_results:
            marker = "PASS" if r["status"] == "ADDRESSED" else r["status"]
            crit = " [CRITICAL]" if r.get("is_critical") and r["status"] == "GAP" else ""
            text_preview = r["text"][:60] + ("..." if len(r["text"]) > 60 else "")
            print(f"  [{marker}]{crit} {r['id']}: {text_preview}")
            if r["status"] != "ADDRESSED":
                print(f"         {r['details']}")

    if faq_results:
        print()
        print("FAQ ITEMS:")
        for r in faq_results:
            marker = "PASS" if r["status"] == "ADDRESSED" else r["status"]
            text_preview = r["text"][:60] + ("..." if len(r["text"]) > 60 else "")
            print(f"  [{marker}] {r['id']}: {text_preview}")
            if r["status"] != "ADDRESSED":
                print(f"         {r['details']}")

    # Gap pattern warnings
    if gap_warnings:
        print()
        print("COMMON GAP PATTERN WARNINGS:")
        print("  The following patterns were NOT detected in the report:")
        for gw in gap_warnings:
            print(f"  - {gw}")

    print()
    if pct >= COVERAGE_THRESHOLD and critical_gaps == 0:
        print("RESULT: PASS")
    else:
        reasons = []
        if pct < COVERAGE_THRESHOLD:
            reasons.append(f"coverage {pct:.0f}% < {COVERAGE_THRESHOLD}%")
        if critical_gaps > 0:
            reasons.append(f"{critical_gaps} CRITICAL gap(s)")
        print(f"RESULT: FAIL ({', '.join(reasons)})")
    print("=" * 70)


def write_coverage_report(
    rubric_results: list[dict],
    faq_results: list[dict],
    gap_warnings: list[str],
    output_path: Path,
) -> None:
    """Write a Markdown coverage report file."""
    all_results = rubric_results + faq_results
    total = len(all_results)
    addressed = sum(1 for r in all_results if r["status"] == "ADDRESSED")
    partial = sum(1 for r in all_results if r["status"] == "PARTIAL")
    gaps = sum(1 for r in all_results if r["status"] == "GAP")
    pct = (addressed / total * 100) if total > 0 else 0
    critical_gaps = sum(
        1 for r in all_results
        if r["status"] == "GAP" and r.get("is_critical")
    )

    lines = [
        "# Rubric Coverage Report",
        "",
        f"**Coverage:** {addressed}/{total} ADDRESSED ({pct:.0f}%)",
        f"**Threshold:** {COVERAGE_THRESHOLD}%",
        f"**PARTIAL:** {partial} | **GAP:** {gaps} | **CRITICAL GAP:** {critical_gaps}",
        f"**Result:** {'PASS' if pct >= COVERAGE_THRESHOLD and critical_gaps == 0 else 'FAIL'}",
        "",
        "---",
        "",
    ]

    if rubric_results:
        lines.append("## Rubric Items")
        lines.append("")
        lines.append("| # | Status | Requirement | Section | Score |")
        lines.append("|---|--------|-------------|---------|-------|")
        for r in rubric_results:
            req = r["text"][:60].replace("|", "\\|")
            crit = " CRITICAL" if r.get("is_critical") and r["status"] == "GAP" else ""
            lines.append(
                f"| {r['id']} | {r['status']}{crit} | {req} | {r['section']} | {r['score']:.2f} |"
            )
        lines.append("")

    if faq_results:
        lines.append("## FAQ Items")
        lines.append("")
        lines.append("| # | Status | Question | Section | Score |")
        lines.append("|---|--------|----------|---------|-------|")
        for r in faq_results:
            q = r["text"][:60].replace("|", "\\|")
            lines.append(
                f"| {r['id']} | {r['status']} | {q} | {r['section']} | {r['score']:.2f} |"
            )
        lines.append("")

    if gap_warnings:
        lines.append("## Common Gap Pattern Warnings")
        lines.append("")
        lines.append("The following common rubric patterns were NOT detected in the report:")
        lines.append("")
        for gw in gap_warnings:
            lines.append(f"- {gw}")
        lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n")
    print(f"  Coverage report written: {output_path}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Check rubric/FAQ compliance of a report file.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python scripts/check_rubric.py --report-path docs/report.tex
    python scripts/check_rubric.py --report-path docs/report.md --rubric-source spec.md --faq-source faq.md
    python scripts/check_rubric.py --report-path docs/report.tex --traceability RUBRIC_TRACEABILITY.md
        """,
    )
    parser.add_argument(
        "--report-path", required=True,
        help="Path to the report file (.tex or .md)",
    )
    parser.add_argument(
        "--rubric-source", default=DEFAULT_RUBRIC_SOURCE,
        help=f"Path to rubric source file (default: {DEFAULT_RUBRIC_SOURCE})",
    )
    parser.add_argument(
        "--faq-source", default=DEFAULT_FAQ_SOURCE,
        help=f"Path to FAQ source file (default: {DEFAULT_FAQ_SOURCE})",
    )
    parser.add_argument(
        "--traceability", default=None,
        help="Path to filled RUBRIC_TRACEABILITY.md (optional)",
    )
    parser.add_argument(
        "--output", default="rubric_coverage.md",
        help="Path for coverage report output (default: rubric_coverage.md)",
    )

    args = parser.parse_args()

    report_path = Path(args.report_path)
    rubric_source = Path(args.rubric_source)
    faq_source = Path(args.faq_source)
    traceability_path = Path(args.traceability) if args.traceability else None
    output_path = Path(args.output)

    print("Rubric / FAQ Compliance Checker")
    print(f"  Report:       {report_path}")
    print(f"  Rubric:       {rubric_source}")
    print(f"  FAQ:          {faq_source}")
    print(f"  Traceability: {traceability_path or '(none)'}")
    print(f"  Output:       {output_path}")
    print()

    # Run checks
    rubric_results, faq_results, gap_warnings = run_checks(
        report_path, rubric_source, faq_source, traceability_path,
    )

    # Generate/update traceability matrix
    trace_output = traceability_path or Path("RUBRIC_TRACEABILITY.md")
    generate_traceability(
        rubric_results, faq_results,
        str(rubric_source), str(faq_source),
        trace_output,
    )

    # Write coverage report
    write_coverage_report(rubric_results, faq_results, gap_warnings, output_path)

    # Print human-readable summary
    print_coverage_report(rubric_results, faq_results, gap_warnings)

    # Exit code
    all_results = rubric_results + faq_results
    total = len(all_results)
    addressed = sum(1 for r in all_results if r["status"] == "ADDRESSED")
    pct = (addressed / total * 100) if total > 0 else 0
    critical_gaps = sum(
        1 for r in all_results
        if r["status"] == "GAP" and r.get("is_critical")
    )

    if pct >= COVERAGE_THRESHOLD and critical_gaps == 0:
        sys.exit(0)
    else:
        sys.exit(1)


if __name__ == "__main__":
    main()
