#!/usr/bin/env bash
# check_phase_3.sh — Gate check for Phase 3 — Migration Recommendations & Findings
# AUTO-GENERATED by gen_phase_gates.py from project.yaml
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

echo "=== Phase 3 — Migration Recommendations & Findings ==="
echo ''

PASSED=0
FAILED=0
ERRORS=()

echo -n "  [1/2] All artifacts verified... "
if python scripts/verify_manifests.py > /dev/null 2>&1; then
    echo "PASS"
    PASSED=$((PASSED + 1))
else
    echo "FAIL"
    FAILED=$((FAILED + 1))
    ERRORS+=("  FAIL: All artifacts verified")
    ERRORS+=("        Command: python scripts/verify_manifests.py")
fi

echo -n "  [2/2] FINDINGS.md exists... "
if test -f FINDINGS.md > /dev/null 2>&1; then
    echo "PASS"
    PASSED=$((PASSED + 1))
else
    echo "FAIL"
    FAILED=$((FAILED + 1))
    ERRORS+=("  FAIL: FINDINGS.md exists")
    ERRORS+=("        Command: test -f FINDINGS.md")
fi

echo ''
echo "=== Results: $PASSED passed, $FAILED failed ==="

if [ $FAILED -gt 0 ]; then
    echo ""
    echo "Failures:"
    for err in "${ERRORS[@]}"; do
        echo "$err"
    done
    echo ""
    echo "Phase gate FAILED. Fix the above issues before proceeding."
    exit 1
fi

echo "Phase 3 — Migration Recommendations & Findings — ALL CHECKS PASSED"
