#!/usr/bin/env bash
# check_phase_0.sh — Gate check for Phase 0 — Environment & Data Acquisition
# AUTO-GENERATED by gen_phase_gates.py from project.yaml
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

echo "=== Phase 0 — Environment & Data Acquisition ==="
echo ''

PASSED=0
FAILED=0
ERRORS=()

echo -n "  [1/3] Environment + imports verified... "
if bash scripts/verify_env.sh > /dev/null 2>&1; then
    echo "PASS"
    PASSED=$((PASSED + 1))
else
    echo "FAIL"
    FAILED=$((FAILED + 1))
    ERRORS+=("  FAIL: Environment + imports verified")
    ERRORS+=("        Command: bash scripts/verify_env.sh")
fi

echo -n "  [2/3] NVD crypto CVEs downloaded... "
if python scripts/check_data_ready.py > /dev/null 2>&1; then
    echo "PASS"
    PASSED=$((PASSED + 1))
else
    echo "FAIL"
    FAILED=$((FAILED + 1))
    ERRORS+=("  FAIL: NVD crypto CVEs downloaded")
    ERRORS+=("        Command: python scripts/check_data_ready.py")
fi

echo -n "  [3/3] Git remote configured... "
if git remote -v > /dev/null 2>&1; then
    echo "PASS"
    PASSED=$((PASSED + 1))
else
    echo "FAIL"
    FAILED=$((FAILED + 1))
    ERRORS+=("  FAIL: Git remote configured")
    ERRORS+=("        Command: git remote -v")
fi

echo ''
echo "=== Results: $PASSED passed, $FAILED failed ==="

if [ $FAILED -gt 0 ]; then
    echo ""
    echo "Failures:"
    for err in "${ERRORS[@]}"; do
        echo "$err"
    done
    echo ""
    echo "Phase gate FAILED. Fix the above issues before proceeding."
    exit 1
fi

echo "Phase 0 — Environment & Data Acquisition — ALL CHECKS PASSED"
