#!/usr/bin/env bash
# check_phase_1.sh — Gate check for Phase 1 — Crypto Detection Engine
# AUTO-GENERATED by gen_phase_gates.py from project.yaml
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

echo "=== Phase 1 — Crypto Detection Engine ==="
echo ''

PASSED=0
FAILED=0
ERRORS=()

echo -n "  [1/1] Detection smoke test... "
if python scripts/run_detection.py --sample-frac 0.01 --seed 42 > /dev/null 2>&1; then
    echo "PASS"
    PASSED=$((PASSED + 1))
else
    echo "FAIL"
    FAILED=$((FAILED + 1))
    ERRORS+=("  FAIL: Detection smoke test")
    ERRORS+=("        Command: python scripts/run_detection.py --sample-frac 0.01 --seed 42")
fi

echo ''
echo "=== Results: $PASSED passed, $FAILED failed ==="

if [ $FAILED -gt 0 ]; then
    echo ""
    echo "Failures:"
    for err in "${ERRORS[@]}"; do
        echo "$err"
    done
    echo ""
    echo "Phase gate FAILED. Fix the above issues before proceeding."
    exit 1
fi

echo "Phase 1 — Crypto Detection Engine — ALL CHECKS PASSED"
