#!/usr/bin/env python3
"""check_integrity.py — Academic integrity checker for ML project reports.

Auto-generated by gen_integrity_checker.py from project.yaml.
Re-run generator after changing project.yaml ai_governance configuration.

Project: Post-Quantum Cryptography Migration Analyzer
"""
import argparse
import os
import re
import sys
from pathlib import Path


# ── Configuration (from project.yaml) ────────────────────────────────────────

TOOL_NAMES = ["Claude Code"]
TOOL_PROHIBITED = {"Claude Code": "Must not interpret migration risk levels (human security judgment). Must not scan private repos without authorization."}
TOOL_PERMITTED = {}
ANTI_GHOSTWRITING = True
DELIVERABLE_PATTERN = ""
AUTHOR_FORMAT = ""


# ── Helpers ───────────────────────────────────────────────────────────────────

def read_report(path: str) -> str:
    """Read report content from .tex or .md file."""
    p = Path(path)
    if not p.exists():
        print(f"ERROR: Report not found: {path}")
        sys.exit(1)
    return p.read_text(encoding="utf-8", errors="replace")


def extract_ai_use_section(content: str, ext: str) -> str | None:
    """Extract the AI Use Statement section from a report.

    Looks for common section headings in both LaTeX and Markdown.
    """
    headings = [
        r"AI\s+Use\s+Statement",
        r"AI\s+Use\s+Disclosure",
        r"AI\s+Disclosure",
        r"Use\s+of\s+AI",
        r"AI\s+Tools?\s+Disclosure",
        r"AI\s+Assistance",
        r"AI\s+Declaration",
    ]
    pattern_str = "|".join(headings)

    if ext == ".tex":
        # Match \section{...} or \subsection{...} etc.
        pattern = re.compile(
            r"\\(?:sub)*section\*?\{[^{}]*(?:" + pattern_str + r")[^{}]*\}"
            r"(.*?)(?=\\(?:sub)*section|\\end\{document\}|\Z)",
            re.DOTALL | re.IGNORECASE,
        )
    else:
        # Markdown: ## AI Use Statement ... until next heading or EOF
        pattern = re.compile(
            r"^#{1,4}\s*(?:" + pattern_str + r").*?$"
            r"(.*?)(?=^#{1,4}\s|\Z)",
            re.DOTALL | re.IGNORECASE | re.MULTILINE,
        )

    match = pattern.search(content)
    if match:
        return match.group(1).strip()
    return None


# ── Check Functions ───────────────────────────────────────────────────────────

def check_ai_use_statement_exists(content: str, ext: str) -> tuple[bool, str, str | None]:
    """Check that an AI Use Statement section exists and is non-empty."""
    section = extract_ai_use_section(content, ext)
    if section is None:
        return False, "AI Use Statement section not found", None
    if len(section.strip()) < 20:
        return False, "AI Use Statement section is empty or trivially short", section
    return True, "AI Use Statement section found", section


def check_first_person(section: str) -> tuple[bool, str]:
    """Check that the AI Use Statement uses first-person voice."""
    # Look for "I" or "my" as standalone words
    if re.search(r"\bI\b", section) or re.search(r"\b[Mm]y\b", section):
        return True, "First-person voice detected"
    return False, "No first-person voice (missing 'I' or 'my' as subject)"


def check_tool_specific(section: str) -> tuple[bool, str]:
    """Check that the statement mentions specific tool names, not just generic 'AI'."""
    if not TOOL_NAMES:
        return True, "No tools configured — skipping tool-specificity check"
    found = [name for name in TOOL_NAMES if name.lower() in section.lower()]
    if found:
        return True, f"Tool-specific: mentions {', '.join(found)}"
    return False, f"No specific tool names found (expected one of: {', '.join(TOOL_NAMES)})"


def check_ownership(section: str) -> tuple[bool, str]:
    """Check for ownership declaration language."""
    ownership_patterns = [
        r"\b(?:my\s+own|I\s+(?:designed|formulated|developed|created|wrote|drew|authored))\b",
        r"\b(?:hypothes[ei]s|conclusions?|analysis|interpretation|design)\s+(?:are|is|were|was)\s+(?:my|mine|entirely)\b",
        r"\b(?:I\s+am\s+(?:solely|fully)\s+responsible)\b",
        r"\b(?:all\s+(?:intellectual|original|creative)\s+(?:work|contributions?))\b",
        r"\b(?:my\s+(?:own\s+)?(?:work|analysis|design|hypothes|conclusions?|interpretation))\b",
    ]
    for pat in ownership_patterns:
        if re.search(pat, section, re.IGNORECASE):
            return True, "Ownership declaration found"
    return False, "No ownership declaration (expected language about design/hypotheses/conclusions being author's own)"


def check_verification(section: str) -> tuple[bool, str]:
    """Check for verification/review statement."""
    verification_patterns = [
        r"\b(?:verif(?:y|ied|ying|ication))\b",
        r"\b(?:review(?:ed|ing)?)\b",
        r"\b(?:check(?:ed|ing)?)\b",
        r"\b(?:validat(?:ed|ing|ion))\b",
        r"\b(?:inspect(?:ed|ing)?)\b",
        r"\b(?:confirm(?:ed|ing)?)\b",
    ]
    for pat in verification_patterns:
        if re.search(pat, section, re.IGNORECASE):
            return True, "Verification statement found"
    return False, "No verification statement (expected mention of verifying/reviewing/checking AI output)"


def check_role_specificity(section: str) -> tuple[bool, str]:
    """Check that the statement describes what AI was used for."""
    role_patterns = [
        r"\bused\s+(?:for|to)\b",
        r"\b(?:assisted|helped)\s+(?:with|in|me)\b",
        r"\b(?:generat(?:ed|ing)|writ(?:e|ing|ten)|creat(?:ed|ing))\b",
        r"\b(?:code|script|test|debug|edit|draft|format|structur)\b",
        r"\b(?:autocomplet|inline|copilot|suggestion)\b",
    ]
    for pat in role_patterns:
        if re.search(pat, section, re.IGNORECASE):
            return True, "Role specificity found (describes what AI was used for)"
    return False, "No role specificity (should describe what AI was used for, not just that it was used)"


def check_anti_ghostwriting(section: str, content: str) -> list[tuple[bool, str]]:
    """Anti-ghostwriting checks when enabled."""
    results = []
    if not ANTI_GHOSTWRITING:
        return results

    # Check prohibited uses are not evident in the report
    for tool_name, prohibited_list in TOOL_PROHIBITED.items():
        for prohibited_use in prohibited_list:
            # Normalize: lowercase, strip whitespace
            norm = prohibited_use.lower().strip()
            # Check if the AI Use Statement explicitly mentions doing the prohibited thing
            # We look for patterns like "used X for <prohibited>" or "X generated <prohibited>"
            sus_patterns = [
                rf"{re.escape(tool_name)}.*?{re.escape(norm)}",
                rf"{re.escape(norm)}.*?{re.escape(tool_name)}",
            ]
            found_violation = False
            for pat in sus_patterns:
                if re.search(pat, section, re.IGNORECASE):
                    found_violation = True
                    break
            if found_violation:
                results.append(
                    (False, f"Anti-ghostwriting: AI Use Statement suggests '{tool_name}' was used for prohibited activity '{prohibited_use}'")
                )
            else:
                results.append(
                    (True, f"Anti-ghostwriting: no evidence '{tool_name}' used for prohibited '{prohibited_use}'")
                )

    # Check that all permitted uses are disclosed
    for tool_name, permitted_list in TOOL_PERMITTED.items():
        tool_mentioned = tool_name.lower() in section.lower()
        if not tool_mentioned and permitted_list:
            results.append(
                (False, f"Anti-ghostwriting: tool '{tool_name}' has permitted uses but is not mentioned in AI Use Statement")
            )
        elif tool_mentioned:
            results.append(
                (True, f"Anti-ghostwriting: tool '{tool_name}' is disclosed in AI Use Statement")
            )

    return results


def check_deliverable_naming(report_path: str) -> tuple[bool, str] | None:
    """Check that report filename matches deliverable pattern if configured."""
    if not DELIVERABLE_PATTERN:
        return None
    filename = Path(report_path).name
    # Convert pattern with {PLACEHOLDERS} to a regex
    regex_str = DELIVERABLE_PATTERN
    regex_str = re.sub(r"\{\{\w+\}\}", r"[\\w.-]+", regex_str)
    regex_str = "^" + regex_str + "$"
    if re.match(regex_str, filename):
        return True, f"Deliverable naming: '{filename}' matches pattern '{DELIVERABLE_PATTERN}'"
    return False, f"Deliverable naming: '{filename}' does not match pattern '{DELIVERABLE_PATTERN}'"


def check_author_format(content: str, ext: str) -> tuple[bool, str] | None:
    """Check that author line matches expected format if configured."""
    if not AUTHOR_FORMAT:
        return None
    if ext == ".tex":
        # Look for \author{...}
        match = re.search(r"\\author\{([^{}]+)\}", content)
        if match:
            author_text = match.group(1).strip()
        else:
            return False, "Author format: no \\author{} found in .tex file"
    else:
        # Markdown: look for "Author:" or "author:" line
        match = re.search(r"^[Aa]uthor:?\s*(.+)$", content, re.MULTILINE)
        if match:
            author_text = match.group(1).strip()
        else:
            return False, "Author format: no author line found in report"

    # Convert format pattern to regex
    regex_str = AUTHOR_FORMAT
    regex_str = re.sub(r"\{\{\w+\}\}", r".+", regex_str)
    if re.match(regex_str, author_text):
        return True, f"Author format: '{author_text}' matches '{AUTHOR_FORMAT}'"
    return False, f"Author format: '{author_text}' does not match expected '{AUTHOR_FORMAT}'"


# ── Report Writer ─────────────────────────────────────────────────────────────

def write_report(results: list[tuple[bool, str]], output_path: str) -> None:
    """Write integrity report to markdown."""
    passed = sum(1 for ok, _ in results if ok)
    failed = sum(1 for ok, _ in results if not ok)
    total = len(results)

    lines = [
        "# Academic Integrity Report",
        "",
        f"**Checks run:** {total}  ",
        f"**Passed:** {passed}  ",
        f"**Failed:** {failed}  ",
        f"**Status:** {'PASS' if failed == 0 else 'FAIL'}",
        "",
        "## Results",
        "",
    ]

    for ok, msg in results:
        icon = "PASS" if ok else "FAIL"
        lines.append(f"- [{icon}] {msg}")

    lines.append("")

    Path(output_path).write_text("\n".join(lines))
    print(f"Integrity report written: {output_path}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Check academic integrity of ML project report")
    parser.add_argument("--report-path", required=True, help="Path to report file (.tex or .md)")
    parser.add_argument("--output", default="integrity_report.md", help="Output path for integrity report")
    args = parser.parse_args()

    report_path = args.report_path
    ext = Path(report_path).suffix.lower()
    content = read_report(report_path)

    results: list[tuple[bool, str]] = []

    # 1. AI Use Statement existence
    exists, msg, section = check_ai_use_statement_exists(content, ext)
    results.append((exists, msg))

    if section:
        # 2. AI Use Statement quality checks
        results.append(check_first_person(section))
        results.append(check_tool_specific(section))
        results.append(check_ownership(section))
        results.append(check_verification(section))
        results.append(check_role_specificity(section))

        # 3. Anti-ghostwriting checks
        results.extend(check_anti_ghostwriting(section, content))
    else:
        results.append((False, "Skipping quality checks — AI Use Statement not found"))

    # 4. Deliverable naming check
    naming_result = check_deliverable_naming(report_path)
    if naming_result is not None:
        results.append(naming_result)

    # 5. Author format check
    author_result = check_author_format(content, ext)
    if author_result is not None:
        results.append(author_result)

    # Print summary
    passed = sum(1 for ok, _ in results if ok)
    failed = sum(1 for ok, _ in results if not ok)
    total = len(results)

    print(f"\nAcademic Integrity Check: {total} checks ({passed} passed, {failed} failed)")
    print("=" * 60)
    for ok, msg in results:
        icon = "PASS" if ok else "FAIL"
        print(f"  [{icon}] {msg}")
    print("=" * 60)

    status = "PASS" if failed == 0 else "FAIL"
    print(f"\nOverall: {status}")

    # Write report
    write_report(results, args.output)

    sys.exit(0 if failed == 0 else 1)


if __name__ == "__main__":
    main()
