#!/usr/bin/env bash
# sweep.sh — Orchestrate all experiments for Post-Quantum Cryptography Migration Analyzer
# AUTO-GENERATED by gen_sweep.py from project.yaml
# Re-run generator after changing project.yaml experiment matrix.
set -euo pipefail

SEEDS="42,123,456"
PARTS="all"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

usage() {
    echo "Usage: bash $0 [--parts {1,2,3,all}] [--seeds SEED_LIST]"
    exit 1
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --parts) PARTS="$2"; shift 2 ;;
        --seeds) SEEDS="$2"; shift 2 ;;
        *) echo "Unknown arg: $1"; usage ;;
    esac
done

IFS=',' read -ra SEED_ARRAY <<< "$SEEDS"
cd "$PROJECT_DIR"
export PYTHONHASHSEED=0

run_part1() {
    echo "=== Part 1: crypto_detection ==="
    for method in regex_scanner ast_parser ml_classifier; do
        for dataset in nvd_crypto github_crypto_usage; do
            for seed in "${SEED_ARRAY[@]}"; do
                echo "  $method / $dataset / seed $seed"
                python scripts/run_detection.py \
                    --sample-frac 1.0
            done
        done
    done
}

run_part2() {
    echo "=== Part 2: priority_scoring ==="
    for method in rule_based ml_scorer hybrid; do
        for seed in "${SEED_ARRAY[@]}"; do
            echo "  $method / seed $seed"
            python scripts/run_scoring.py \
                --method $method --seed $seed
        done
    done
}

run_part3() {
    echo "=== Part 3: migration_recommendation ==="
    for method in nist_mapping risk_weighted; do
        for seed in "${SEED_ARRAY[@]}"; do
            echo "  $method / seed $seed"
            python scripts/run_recommendations.py \
                --method $method --seed $seed
        done
    done
}

case "$PARTS" in
    1) run_part1 ;;
    2) run_part2 ;;
    3) run_part3 ;;
    all) run_part1; run_part2; run_part3 ;;
    *) echo "Unknown part: $PARTS"; usage ;;
esac

echo ''
echo "=== Sweep complete ==="
