#!/usr/bin/env python3
"""verify_manifests.py — Verify integrity of all experiment artifacts.

Auto-generated by gen_manifest_verifier.py from project.yaml.
Re-run generator after changing project.yaml artifact configuration.

Project: Post-Quantum Cryptography Migration Analyzer
"""
import hashlib
import json
import sys
from pathlib import Path


HASH_ALGORITHM = "sha256"
MANIFEST_FILE = "outputs/manifest.json"
EXPECTED_PER_RUN = ["summary.json", "config_resolved.yaml"]
OUTPUTS_DIR = Path("outputs")


def compute_hash(filepath: Path) -> str:
    """Compute sha256 hash of a file."""
    h = hashlib.new(HASH_ALGORITHM)
    with open(filepath, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def find_run_dirs() -> list[Path]:
    """Find all run directories (dirs containing summary.json)."""
    if not OUTPUTS_DIR.exists():
        return []
    return sorted(d.parent for d in OUTPUTS_DIR.rglob("summary.json"))


def verify_run(run_dir: Path) -> tuple[int, int, list[str]]:
    """Verify a single run directory. Returns (pass_count, fail_count, errors)."""
    passed = 0
    failed = 0
    errors = []

    # Check expected files exist
    for fname in EXPECTED_PER_RUN:
        fpath = run_dir / fname
        if fpath.exists():
            passed += 1
        else:
            failed += 1
            errors.append(f"  MISSING: {fpath}")

    # Check manifest if it exists
    manifest_path = run_dir / "run_manifest.json"
    if manifest_path.exists():
        try:
            manifest = json.loads(manifest_path.read_text())
            for entry in manifest.get("files", []):
                fpath = run_dir / entry["name"]
                expected_hash = entry.get("hash", entry.get("sha256", ""))
                if not fpath.exists():
                    failed += 1
                    errors.append(f"  MISSING (in manifest): {fpath}")
                    continue
                actual_hash = compute_hash(fpath)
                if actual_hash == expected_hash:
                    passed += 1
                else:
                    failed += 1
                    errors.append(
                        f"  HASH MISMATCH: {fpath}\n"
                        f"    expected: {expected_hash}\n"
                        f"    actual:   {actual_hash}"
                    )
        except (json.JSONDecodeError, KeyError) as e:
            failed += 1
            errors.append(f"  MANIFEST PARSE ERROR: {manifest_path}: {e}")
    else:
        # No per-run manifest — just verify files exist and compute hashes
        for fpath in run_dir.iterdir():
            if fpath.is_file() and fpath.name not in ("run_manifest.json",):
                passed += 1  # File exists, no expected hash to compare

    return passed, failed, errors


def build_global_manifest(run_dirs: list[Path]) -> dict:
    """Build a global manifest of all artifacts with hashes."""
    manifest = {"generated_by": "verify_manifests.py", "algorithm": HASH_ALGORITHM, "runs": {}}
    for run_dir in run_dirs:
        run_id = str(run_dir.relative_to(OUTPUTS_DIR))
        files = {}
        for fpath in sorted(run_dir.rglob("*")):
            if fpath.is_file():
                rel = str(fpath.relative_to(run_dir))
                files[rel] = compute_hash(fpath)
        manifest["runs"][run_id] = files
    return manifest


def main():
    run_dirs = find_run_dirs()

    if not run_dirs:
        print("No experiment runs found in outputs/")
        print("Run experiments first, then verify.")
        sys.exit(0)

    total_passed = 0
    total_failed = 0
    all_errors = []

    print(f"Verifying {len(run_dirs)} experiment runs...\n")

    for run_dir in run_dirs:
        passed, failed, errors = verify_run(run_dir)
        total_passed += passed
        total_failed += failed

        status = "PASS" if failed == 0 else "FAIL"
        run_id = run_dir.relative_to(OUTPUTS_DIR)
        print(f"  [{status}] {run_id} ({passed} passed, {failed} failed)")

        if errors:
            all_errors.extend([f"Run: {run_id}"] + errors)

    print(f"\n=== Summary: {total_passed} passed, {total_failed} failed across {len(run_dirs)} runs ===")

    if all_errors:
        print("\nErrors:")
        for e in all_errors:
            print(e)

    # Write global manifest
    manifest = build_global_manifest(run_dirs)
    manifest_path = Path(MANIFEST_FILE)
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"\nGlobal manifest written: {manifest_path}")

    sys.exit(1 if total_failed > 0 else 0)


if __name__ == "__main__":
    main()
